version: '3'

networks:
  java-net:
    driver: bridge

services:

  # postgresql(RDBMS)
  postgres-server:
    image: postgres:13
    networks:
      - java-net
    container_name: postgresContainer
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
    volumes:
      - .\postgres\docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
  
  # CRUD web API(java)
  crud-api-java-server:
    build:
      context: .\java
      dockerfile: Dockerfile
    container_name: crudApiJavaContainer
    networks:
      - java-net
    ports:
      - '8080:80'
    depends_on:
      - postgres-server

  # Lock or compensating for 2Phase Commit(KVS)
  redis-server:
    image: redis:6-buster
    container_name: redisContainer
    networks:
      - java-net
    ports:
      - '6379:6379'

  # kafka(choreography)
  zookeeper-server:
    image: 'bitnami/zookeeper:latest'
    networks:
      - java-net
    container_name: zookeeperContainer
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka-server:
    image: 'bitnami/kafka:latest'
    networks:
      - java-net
    container_name: kafkaContainer
    ports:
      - '9092:9092'
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper-server:2181
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper-server


